spring:
  application:
    name: uggame-service-security
  profiles:
    active: dev
  cloud:
    nacos:
      #配置中心
      config:
        enabled: false
        server-addr: 192.168.1.1:8848
        namespace: 587a12c3-aace-4759-b79f-b6e7f3b152b8
        file-extension: yml
        # 扩展配置
        extension-configs[0]:
          # 主配置
          - dataId: application.yml
            group: DEFAULT_GROUP

      #服务注册和发现
      discovery:
        register-enabled: false
        server-addr: 192.168.1.1:8848
        namespace: 587a12c3-aace-4759-b79f-b6e7f3b152b8
  #---------------------------------------------------jackson-------------------------------------------------
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  #---------------------------------------------------datasource---------------------------------------------
  datasource:
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    database: uggame
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: 'stat,wall,slf4j'
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    poolPreparedStatements: false
    initialSize: 5
    minIdle: 5
    maxActive: 500
    maxWait: 30000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 1000
    validationQuery: 'select ''x'''
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000


  #---------------------------------------------------redis--------------------------------------------------
  redis:
    timeout: 30000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1
        min-idle: 10


#---------------------------------------------------feign-----------------------------------------------------
feign:
  circuitbreaker:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true

#---------------------------------------------------ribbon----------------------------------------------------
ribbon:
  ServerListRefreshInterval: 1000
  ConnectTimeout: 10000
  ReadTimeout: 30000
  #默认只对get请求重试，设置true时，post请求也会重试。
  OkToRetryOnAllOperations: false
  #是每台服务器最多重试次数，，但是首次调用不包括在内
  MaxAutoRetries: 1
  #是最多重试多少台服务器。
  MaxAutoRetriesNextServer: 2
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule


#---------------------------------------------------hystrix----------------------------------------------------
hystrix:
  threadpool:
    default:
      coreSize: 100
      maximumSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 100
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000

#---------------------------------------------------日志打印输出过滤配置-------------------------------------------------
stdio:
  filter:
    # 出参日志过滤配置
    outFilter:
      classNames:
        - ""
      methods:
        - ""
    # 入参日志过滤配置
    inFilter:
      classNames:
        - ""
      methods:
        - ""


#---------------------------------------------------management-------------------------------------------------
management:
  security:
    enabled: false
  info:
    git:
      mode: full

server:
  port: 8888

swagger:
  basePackage: com.dofun.uggame
  apiInfo:
    title: '安全服务'
    name: 'Steven Cheng'
    description: '安全服务'
    email: 'stevencheng@dofun.cn'
    version: 'v1.0.0'

encryption:
  key: 'df831c18fa703096'
  type: 'rc4'

client:
  type: 'garenaPasswordAgent'
  auth:
    ticketTime: 86400

