spring:
  #---------------------------------------------------datasource---------------------------------------------
  datasource:
    ip: rm-t4nzvt45h12zoy285.mysql.singapore.rds.aliyuncs.com
    port: 3306
    username: uggameen
    database: uggameen
    password: qaQ2ojYNyt1ktN5w


  #---------------------------------------------------redis--------------------------------------------------
  redis:
    host: 10.0.65.70
    port: 6379


httpsqs:
  ip: '10.0.65.70'
  port: 1218
  auth: ''

client:
  auth:
    #username 唯一
    username: 'prod'
    password: 'xBLlofhYXL4PqtVt'

