spring:
  cloud:
    nacos:
      #配置中心
      config:
        enabled: false
      #服务注册和发现
      discovery:
        register-enabled: false

  application:
    name: uggame-service-security
  #---------------------------------------------------jackson-------------------------------------------------
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #---------------------------------------------------datasource---------------------------------------------
  datasource:
    url: jdbc:mysql://${spring.datasource.ip}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false
    ip: 161.117.249.164
    port: 3306
    username: uggame
    password: Rzs5yHw3CDsxzFY4
    database: uggame
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: 'stat,wall,slf4j'
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    poolPreparedStatements: false
    initialSize: 5
    minIdle: 5
    maxActive: 500
    maxWait: 30000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 1000
    validationQuery: 'select ''x'''
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000


  #---------------------------------------------------redis--------------------------------------------------
  redis:
    timeout: 30000
    host: 161.117.249.164
    port: 6379
    pool:
      max-active: 1000
      max-idle: 100
      max-wait: -1
      min-idle: 10

server:
  port: 8888

swagger:
  basePackage: com.dofun.uggame
  apiInfo:
    title: '安全服务'
    name: 'Steven Cheng'
    description: '账号管理服务description'
    email: 'stevencheng@dofun.cn'
    version: 'v1.0.0'

encryption:
  key: 'df831c18fa703096'
  type: 'rc4'

