spring:
  #---------------------------------------------------datasource---------------------------------------------
  datasource:
    ip: 10.0.65.67
    port: 3306
    username: uggame
    password: Rzs5yHw3CDsxzFY4


  #---------------------------------------------------redis--------------------------------------------------
  redis:
    host: 10.0.65.67
    port: 6379


httpsqs:
  ip: '10.0.65.67'
  port: 1218
  auth: ''

client:
  auth:
    #username 唯一
    username: 'test'
    password: '123456'

