spring:
  #---------------------------------------------------datasource---------------------------------------------
  datasource:
    ip: 161.117.249.164
    port: 3306
    username: uggame
    password: Rzs5yHw3CDsxzFY4


  #---------------------------------------------------redis--------------------------------------------------
  redis:
    host: 161.117.249.164
    port: 6379


httpsqs:
  ip: '161.117.249.164'
  port: 1218
  auth: ''

client:
  auth:
    #username 唯一
    username: 'test'
    password: '123456'

